server:
  port: 8082

spring:
  application:
    name: "member"

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: lms
    password: lms
    driver-class-name: oracle.jdbc.driver.OracleDriver
  config:
    import: "configserver:http://localhost:8071"

logging:
  level:
    root: INFO
  
  file:
    name: logs/member-service.log

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8070/eureka/