server:
  port: 8082

spring:
  application:
    name: MEMBER-SERVICE

  datasource:
    url: jdbc:oracle:thin:@localhost:1521/FREEPDB1
    username: lms
    password: lms
    driver-class-name: oracle.jdbc.driver.OracleDriver

logging:
  level:
    root: INFO
  
  file:
    name: logs/member-service.log